import { NextRequest, NextResponse } from "next/server";
import { updateSession } from "@/lib/supabase/middleware";

export const config = {
  matcher: [
    /*
     * Match all paths except for:
     * 1. /api routes
     * 2. /_next (Next.js internals)
     * 3. /_static (inside /public)
     * 4. all root files inside /public (e.g. /favicon.ico)
     */
    "/((?!api/|_next/|_static/|_vercel|[\\w-]+\\.\\w+).*)",
  ],
};

export default async function middleware(req: NextRequest) {
  // 1. Refresh Supabase session first
  // This sets the cookies on the response
  const response = await updateSession(req);
  
  // If updateSession returns a redirect or rewrite (it currently doesn't, just next()),
  // we can continue. But we need to make sure we carry over the cookies set by Supabase
  // to our final response.
  
  const url = req.nextUrl;
  const hostname = req.headers.get("host")!;

  // Define the domains
  const appDomain = process.env.NEXT_PUBLIC_APP_DOMAIN || "app.simupa.web.id";
  const isAppSubdomain = hostname === appDomain || hostname.startsWith("app.");

  // If user visits app subdomain, rewrite to /app path
  // This allows app.localhost:3000 to show the content of /app
  // If user visits app subdomain, rewrite to /app path
  // This allows app.localhost:3000 to show the content of /app
  if (isAppSubdomain) {
    // If the path is just "/", rewrite to "/app"
    if (url.pathname === "/") {
      return NextResponse.rewrite(new URL("/app", req.url));
    }

    // Allow Login and Register on App Subdomain to support host-only cookies in dev
    if (url.pathname === "/login") {
      return NextResponse.rewrite(new URL("/login", req.url));
    }
    if (url.pathname === "/daftar") {
      return NextResponse.rewrite(new URL("/daftar", req.url));
    }

    // Special case: Do not rewrite /icon (generated by src/app/icon.tsx)
    if (url.pathname === "/icon") {
      return NextResponse.next();
    }
    
    // For other paths, rewrite to /app/path
    return NextResponse.rewrite(new URL(`/app${url.pathname}`, req.url));
  }

  // Handle Login Subdomain
  if (hostname.startsWith("login.")) {
    return NextResponse.rewrite(new URL("/login", req.url));
  }

  // Handle Register Subdomain
  if (hostname.startsWith("daftar.") || hostname.startsWith("register.")) {
    return NextResponse.rewrite(new URL("/daftar", req.url));
  }

  // If we are on the landing domain (or any other domain), serve the root content
  // which is now the Landing Page (src/app/page.tsx)
  return response;
}
